# file map -> binary map
loading_path: "/home/yabao/output/M2DGR/gate_03"                                          # file map path
binarymapName: "/media/yabao/TOSHIBA1/output/M2DGR/with_corner_surf/gate_03_map.bin"      # binary map
lidar_keyFrame_num: 197                                                                   # lidar关键帧数

# relocation
QUERY_PATH: "/media/yabao/TOSHIBA1/Datasets/M2DGR/rosbag2file/gate_02"
QUERY_LIDAR_PATH: ""
QUERY_IMAGE_PATH: ""


# 0:激光视觉融合重定位；1:视觉重定位；2：激光重定位 
RELOCATE_METHOD: 0
# env info test
ENV_LIDAR_PATH: "/home/yabao/slam/lvi_sam_location/test_data/gate01_2.pcd"
DENSE_DIS: 20          # 判定为密集空间需要的距离
DENSE_RATIO: 0.40       # 判定为密集空间需要点的百分比
OPEN_DIS: 40            # 判定为开阔空间需要的距离
OPEN_RATIO: 0.80        # 判定为开阔空间需要点的百分比
USE_TUNNING: 1          # 是否使用新参数
