# file map -> binary map
POSE_GRAPH_SAVE_PATH: "/home/yabao/output/M2DGR/street_02/camera/pose_graph/"     # visual map
loading_path: "/home/yabao/output/M2DGR/street_02"                                # lidar map
binarymapName: "street_02_map.bin"                                                # binary map
lidar_keyFrame_num: 790                                                           # lidar关键帧数

# relocation
QUERY_PATH: "/media/yabao/TOSHIBA1/Datasets/M2DGR/rosbag2file/street_06"
QUERY_LIDAR_PATH: ""
QUERY_IMAGE_PATH: ""

# location
# use in run_kitti.cpp and run_m2dgr.cpp
DATASET_PATH: /media
START_FRAME: 800
END_FRAME: 900

# test
# 0:激光视觉融合重定位；1:视觉重定位；2：激光重定位 
RELOCATE_METHOD: 0
# env info test
ENV_LIDAR_PATH: "/media/yabao/TOSHIBA1/Datasets/M2DGR/rosbag2file/gate_01/pcd/1627729626.916651011.pcd"
DENSE_DIS: 10           # 判定为密集空间需要的距离
DENSE_RATIO: 0.3        # 判定为密集空间需要点的百分比
OPEN_DIS: 50            # 判定为开阔空间需要的距离
OPEN_RATIO: 0.95        # 判定为开阔空间需要点的百分比
USE_TUNNING: 1          # 是否使用调参
