# file map -> binary map
POSE_GRAPH_SAVE_PATH: "/home/yabao/output/KITTI/2011_09_30_drive_0027_07/camera/pose_graph/"     # visual map
loading_path: "/home/yabao/output/KITTI/2011_09_30_drive_0027_07"                                # lidar map
binarymapName: "/media/yabao/TOSHIBA1/output/KITTI/with_corner_surf/2011_09_30_drive_0027_07_map.bin"                                                # binary map (save name and load name)
lidar_keyFrame_num: 424                                                                          # lidar关键帧数

# relocation
QUERY_PATH: "/media/yabao/TOSHIBA1/Datasets/KITTI/raw_data/2011_09_30_drive_0027_07/2011_09_30/2011_09_30_drive_0027_sync"
QUERY_LIDAR_PATH: ""
QUERY_IMAGE_PATH: ""

# test
# 0:激光视觉融合重定位；1:视觉重定位；2：激光重定位 
RELOCATE_METHOD: 0
# env info test
ENV_LIDAR_PATH: "/home/yabao/slam/lvi_sam_location/test_data/gate01_1.pcd"
DENSE_DIS: 20           # 判定为密集空间需要的距离
DENSE_RATIO: 0.40        # 判定为密集空间需要点的百分比
OPEN_DIS: 40            # 判定为开阔空间需要的距离
OPEN_RATIO: 0.80        # 判定为开阔空间需要点的百分比
USE_TUNNING: 1          # 是否使用调参

